### ISSUE TITLE
utf-*

### ISSUE THREAD

**Issue by fab1an2** [CosmicToast/bread.h#1]
how implementing utf-8 16, 32 etc
this is important

**Comment by CosmicToast** [comment]
What exactly does not work with UTF-8?
Or are you asking for a tutorial on how to write UTF-8 compatible programs?
I don't understand what you're requesting here.

**Comment by CosmicToast** [comment]
Because you don't seem to be the only one with this misconception, I added a test for utf-8.
You are welcome to compile it yourself, and note that UTF-8 functions just fine.
https://github.com/CosmicToast/bread.h/commit/0d746c74a40f207d97a7d8892c3969dff7f53c9d
Demo here:
<img width="752" alt="image" src="https://github.com/CosmicToast/bread.h/assets/5273047/1b1dc1f9-0bb7-4a61-95d5-e126d3974f1f">
Note that no code changes were necessary, it worked fine to begin with. Same goes for stdiox and base64.
